# Generated by Django 4.2.18 on 2025-02-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_active_code',
            field=models.IntegerField(default=85635, verbose_name='کد فعالسازی شماره'),
        ),
    ]
